import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { ToastContainer } from "react-toastify";
import { Inter } from "next/font/google";
import Layout from "./LayoutProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Providers>
          <Layout>
            {children}
            <ToastContainer />
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
